services:
  ros1-main-program:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: ohin112/rosentralytics:cb
    container_name: build
    tty: true
    privileged: true
    network_mode: host

    environment:
      - DISPLAY=${DISPLAY} 

    volumes:
      - $HOME/cb/extraction-ws:/home/extraction-ws
      - $HOME/cb/realsense-ws:/home/realsense-ws
      - $HOME/cb/startup:/home/startup
      
    command: >
      /bin/bash -ic "
      cd /home/extraction-ws 
      && catkin_make
      && chmod +x /home/extraction-ws/devel/*
      && cd /home/realsense-ws 
      && catkin_make
      "